# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: pwnstyles_rails 0.2.1 ruby lib

Gem::Specification.new do |s|
  s.name = "pwnstyles_rails"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Victor Costan"]
  s.date = "2014-12-15"
  s.description = "Included CSS was designed for reuse across pwnb.us apps."
  s.email = "victor@costan.us"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".project",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/assets/images/pwnstyles/select-arrow-emph.svg",
    "app/assets/images/pwnstyles/select-arrow.svg",
    "app/assets/javascripts/pwn-fx.js.coffee",
    "app/assets/stylesheets/_pwnplus.scss",
    "app/assets/stylesheets/_pwnstyles.scss",
    "app/assets/stylesheets/elements/_buttons.scss",
    "app/assets/stylesheets/elements/_figures.scss",
    "app/assets/stylesheets/elements/_forms.scss",
    "app/assets/stylesheets/elements/_images.scss",
    "app/assets/stylesheets/elements/_inputs.scss",
    "app/assets/stylesheets/elements/_links.scss",
    "app/assets/stylesheets/elements/_lists.scss",
    "app/assets/stylesheets/elements/_tables.scss",
    "app/assets/stylesheets/elements/_text.scss",
    "app/assets/stylesheets/generic/_pwnfx.scss",
    "app/assets/stylesheets/generic/_reset.scss",
    "app/assets/stylesheets/modules/_body.scss",
    "app/assets/stylesheets/modules/_footer.scss",
    "app/assets/stylesheets/modules/_header.scss",
    "app/assets/stylesheets/modules/_status_bar.scss",
    "app/assets/stylesheets/pwnplus/_buttons.scss",
    "app/assets/stylesheets/pwnplus/_form_fields.scss",
    "app/assets/stylesheets/pwnplus/_hacks.scss",
    "app/assets/stylesheets/pwnplus/_menu_bar.scss",
    "app/assets/stylesheets/vars/_color_scheme.scss",
    "app/assets/stylesheets/vars/_fonts.scss",
    "app/assets/stylesheets/vars/_layout_sizes.scss",
    "config/initializers/fix_fields_with_errors.rb",
    "lib/pwnstyles_rails.rb",
    "lib/pwnstyles_rails/engine.rb",
    "lib/pwnstyles_rails/generators/all_generator.rb",
    "lib/pwnstyles_rails/generators/assets/stylesheets/pwnstyles/_app_vars.scss",
    "lib/pwnstyles_rails/generators/assets/stylesheets/pwnstyles/pwnstyles_main.scss",
    "lib/pwnstyles_rails/generators/layouts/_footer.html.erb",
    "lib/pwnstyles_rails/generators/layouts/_header.html.erb",
    "lib/pwnstyles_rails/generators/layouts/_menu.html.erb",
    "lib/pwnstyles_rails/generators/layouts/_status_bar.html.erb",
    "lib/pwnstyles_rails/generators/layouts/application.html.erb",
    "pwnstyles_rails.gemspec",
    "test/helper.rb",
    "test/test_pwnstyles_rails.rb"
  ]
  s.homepage = "http://github.com/pwnall/pwnstyles_rails"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Rails 3 SCSS integration and non-trivial default style."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sass-rails>, [">= 5.0.0"])
      s.add_runtime_dependency(%q<rails>, [">= 4.1.8"])
      s.add_development_dependency(%q<minitest>, [">= 3.4.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.6.0"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1"])
    else
      s.add_dependency(%q<sass-rails>, [">= 5.0.0"])
      s.add_dependency(%q<rails>, [">= 4.1.8"])
      s.add_dependency(%q<minitest>, [">= 3.4.0"])
      s.add_dependency(%q<bundler>, [">= 1.6.0"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1"])
    end
  else
    s.add_dependency(%q<sass-rails>, [">= 5.0.0"])
    s.add_dependency(%q<rails>, [">= 4.1.8"])
    s.add_dependency(%q<minitest>, [">= 3.4.0"])
    s.add_dependency(%q<bundler>, [">= 1.6.0"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1"])
  end
end
